name: bolt-expressions-source-inheritance

data_pack:
  load:
    data/test/functions: src

require:
  - bolt_expressions
  - bolt

pipeline:
  - mecha

output: dist

meta:
  generate_namespace: test
