name: bolt-expressions-nbt-type

data_pack:
  pack_format: 10
  load:
    data/test/functions: src

require:
  - bolt
  - bolt_expressions

pipeline:
  - mecha

output: dist

meta:
  generate_namespace: test
